### PR TITLE
Feat commit rule

### PR DESCRIPTION
**Pull request by xavierchow**

### CODE REVIEW

**Comment by xavierchow** [comment]
@makara You mean the `type part`(feat/chore/fix ...)? (https://github.com/marionebl/commitlint/tree/master/%40commitlint/config-conventional#type-case), it's configurable but I'd like to hear others options, personally I have no bias.

**Comment by makara** [comment]
Well I mean I usually write something more complete like "Added a helper that does xxx" or "Fixed a bug where xxx" etc. but I don't mind writing it like a geek either.

**Comment by ole3021** [comment]
Personally, i love the UpperCase for the Type (even inside brackets) which I think it can make it very obvious to other people. 
eg: `[FIXED] Some critical bug...`

**Comment by xavierchow** [comment]
@makara alright, I see you are misunderstanding the `type`, it doesn't have to be a verb, it's just a tag, you can still write the commit message in a sentence-style.

**Comment by xavierchow** [comment]
so, do you prefer
`chore: set up commitlint with husky`

or 
`CHORE: set up commitlint with husky`

**Comment by makara** [comment]
I think either:

```
chore: set up commitlint with husky
```

or 

```
[CHORE] Set up commitlint with husky
```

again I don't mind making it more geeky, just `chore:` can feel like it's part of the sentence and personally I think it's confusing and not strict enough.

**Comment by ole3021** [comment]
vote for `[CHORE]`

**Comment by xavierchow** [comment]
Type in square brackets is not in the scope of `conventional commit`(https://conventionalcommits.org/), you can only make the type uppercase without breaking the whole format.

> chore: set up commitlint with husky
or
CHORE: set up commitlint with husky

**Pull request merged**
