### PR TITLE
chore: remove loopback-component-explorer

### LINKED ISSUE #66: Upgrade dependencies
Plenty of high severity issues in the current repo. 

Need to address them.

Screen Shot 2019-08-06 at 10 20 35

/cc @xavierchow - please assign to whomever can address it.

### PR DESCRIPTION
**Pull request by Zacharysp**
resolve #66 

remove `loopback-component-explorer` entirely. [reference](https://github.com/Wiredcraft/api-boilerplate/pull/71#issuecomment-542530232)

### CODE REVIEW

**Comment by xavierchow** [comment]
adding more reviewers.

**Comment by xavierchow** [comment]
@Zacharysp I approved, but let's wait for 1~2 days to hear the voice from other developers.

**Comment by pivstone** [comment]
@xavierchow  If I correct, @ChopperLee2011  is using explorer at goat.

**Comment by xavierchow** [comment]
> If I correct, @ChopperLee2011 is using explorer at goat.

I suppose it's not for production, right?

**Comment by ChopperLee2011** [comment]
1. loopback-component-explorer is enabled for dev, maybe staging, not production.
2. loopback-component-explorer is an independent component for Loopback.

**Comment by woodpig07** [comment]
For local development, I do need to use `/explorer` to do some quick API tests from time to time.
But agree to remove it from boilerplate because of the security risk.

**Comment by xavierchow** [comment]
> For local development, I do need to use /explorer to do some quick API tests from time to time.

The loopback explorer is just one of many approaches that work as the client of API with local started service, you can achieve the target with curl, postman, or even better with test code.

**Comment by woodpig07** [comment]
Another trick I do with `loopback-component-explorer` is that it can quickly tell me if I configure the methods via `disableRemoteMethods` correctly. ---- not a great habit, I know 🙍

**Pull request merged**
