### PR TITLE
refactor: switch to jest

### PR DESCRIPTION
**Pull request by ole3021**
- [x] replace mocha test cases with jest
- [x] use jest to do `test` and `test-cov`
- [x] restructure the test files structure
- [x] rewrite all test cases and expects.

### CODE REVIEW

**Comment by makara** [comment]
Can we don't include "prettier" in your every PRs until we get a common agreement?

**Comment by ole3021** [comment]
ok

**Comment by ole3021** [comment]
@makara @JuhaS @xavierchow Have fixed some integration problem. and rebased on the master branch. please have a look

**Comment by wwayne** [comment]
Just curious, why switching the test frame to Jest?
I use Jest only for frontend testing because of the snapshot. For the backend, Jest and Mocha are the same in most cases, I remember Jest had a lot of bugs till last year, I'm not sure if it is stable enough.

**Comment by ole3021** [comment]
@wwayne  check the video. https://www.youtube.com/watch?v=cAKYQpTC7MA

**Comment by woodpig07** [comment]
I think Jest is very promising on performance, which is the reason that I'm willing to try it on new projects. But all the projects I'm currently maintained are with Mocha, so I don't want to dump Mocha from our api boilerplate completely.
Can we have some feature branches (or example folders) for major libraries or dev tools combination change, such as
- `loopback3-coubase3-macha`
- `loopback3-coubase3-jest`
- `loopback4-coubase4-jest`
- `loopback4-coubase5-jest`

**Comment by xavierchow** [comment]
Agreed with @woodpig07, @ole3021 can you rebase against master and keep it in a feature branch, we will try it on new projects.

**Comment by wwayne** [comment]
I switched to Jest in omni-notification because your points make sense, but I found sth inconvenient:
1. We can't use `only` to specify a test case in a specific test file, Jest loads all test files anyway, `only` means in this single test file, run this test case. unless specify in cli `jest path/specific.test.js`
2. Expect from Jest doesn't support chain, so `expect(sth).toHaveProperty('sth').toBeInstance(Array)` doesn't work

**Comment by ole3021** [comment]
@xavierchow the conflicts have been fixed.

**Comment by ole3021** [comment]
@wwayne 

1. you can use `.skip` to skip some test cases in the test.
2. why not write `expect(sth[sth]). toBeInstance(Array)`, the chain method can be very long and hard to understand sometimes.

**Comment by xavierchow** [comment]
> you can use .skip to skip some test cases in the test.

The purpose and use case of `skip` and `only` are different, sometimes I need to turn on a single test case to see why it fails,  you won't like to skip all the other cases(might be massive)

**Comment by ole3021** [comment]
@wwayne @xavierchow For the `only` issue

You do can use `describe.only` and `it.only` to skip other test cases.

also, there is a better solution execute command ` jest --runTestsByPath xxxx` can only do jest on the sepcific file.

For me, I personally use `jest --watch` or `jest --watchAll` during the TDD process. 

here is more details https://jestjs.io/docs/en/cli.html

**Comment by wwayne** [comment]
@ole3021 Seems `describe.only` can't skip test cases in other test files

**Comment by ole3021** [comment]
@wwayne not really using this in my previous works. 

check this out. https://stackoverflow.com/questions/44446626/run-only-one-test-with-jest

**Comment by wwayne** [comment]
@ole3021 understood, `watch` seems very useful if you prefer TDD, I supposed that's why you won't have such issue

**Comment by xavierchow** [comment]
One of inconvenience I found: https://github.com/facebook/jest/issues/3457

**Pull request merged**
